config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'opinions#index'
  resources :users, only: %i[new create edit update]
  resources :opinions, only: [:index, :create] do
  	resources :comments, only: [:create]
  end
  get 'sessions/new'
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'logout', to: 'sessions#destroy'
  post 'opinion', to: 'opinions#create'
  post 'follow', to: 'followings#create'
  get 'follow', to: 'followings#create'
  get 'users/:username', to: 'users#show', as: 'profile'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true, length: { maximum: 200, too_long: 'maximum 200 characters allowed.' }

  belongs_to :user
  belongs_to :opinion
end

app/models/following.rb
class Following < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
end

app/models/opinion.rb
class Opinion < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :destroy

  validates :text, presence: true, length: { minimum: 4, maximum: 300 }
  scope :order_by_most_recent, -> { includes(:author).order(created_at: :desc) }
end

app/models/user.rb
class User < ApplicationRecord
  has_attached_file :photo
  has_attached_file :cover_image

  validates :username, presence: true, uniqueness: true, length: { minimum: 3, maximum: 20 }
  validates :fullname, presence: true, length: { minimum: 5, maximum: 30 }
  validates_attachment_content_type :photo, :cover_image, content_type: ['image/jpg', 'image/jpeg', 'image/png']

  has_many :opinions, foreign_key: 'author_id', dependent: :destroy
  has_many :followings, class_name: 'Following', foreign_key: 'follower_id'
  has_many :follows, through: :followings, source: :followed
  has_many :inverse_followings, class_name: 'Following', foreign_key: 'followed_id'
  has_many :followers, through: :inverse_followings, source: :follower
  has_many :comments, dependent: :destroy

  def who_to_follow
    User.where.not(id: id).where.not(id: follows).order('created_at DESC')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by(username: session[:username]) if session[:username]
  end

  def logged_in?
    !current_user.nil?
  end

  def require_user
    return if logged_in?

    flash[:danger] = 'Log in to perform this action'
    redirect_to sign_in_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @comment.opinion_id = params[:opinion_id]
    @comment.user = current_user

    if @comment.save
      redirect_to opinions_path, notice: 'Comment was successfully created.'
    else
      redirect_to opinions_path, alert: @comment.errors.full_messages.join('. ').to_s
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController
  def create
    @following = current_user.followings.new(followed_id: params[:user_id])
    if @following.save
      flash[:notice] = "You are following #{User.find(params[:user_id]).fullname}"
    else
      flash[:alert] = 'Something went wrong ...'
    end
    redirect_to root_path
  end
end

app/controllers/opinions_controller.rb
class OpinionsController < ApplicationController
  before_action :require_user

  def index
    @opinion = Opinion.new
    @opinions = Opinion.order_by_most_recent
    @not_follow = current_user.who_to_follow
  end

  def create
    @opinion = current_user.opinions.build(opinion_params)
    if @opinion.save
      flash[:notice] = 'Opinion was created successfully'
      redirect_to root_path
    else
      flash.now[:alert] = 'Something went wrong...'
    end
  end

  private

  def opinion_params
    params.require(:opinion).permit(:text)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # def new
  # end

  def create
    @user = User.find_by(username: params[:session][:username])

    if @user
      session[:username] = @user.username
      flash[:success] = 'successfully signed in'
      redirect_to root_path
    else
      flash.now[:danger] = 'Oopps! Something wrong'
      render 'new'
    end
  end

  def destroy
    session[:username] = nil
    flash[:success] = 'You have successfully logged out'
    redirect_to sign_in_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user, except: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = User.create(signup_params)
    if @user.save
      flash[:success] = 'Account is created sucessfully'
      session[:username] = @user.username
      redirect_to root_path
    else
      flash[:danger] = 'Something went wrong'
      render new_user_path
    end
  end

  def show
    @user = User.find_by(username: params[:username])
    @opinion = Opinion.new
    @opinions = @user.opinions.order_by_most_recent
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    @user.update(signup_params)

    flash.notice = "'#{user.username}' profile updated!"
    redirect_to profile_path(@user.username)
  end

  private

  def signup_params
    params.require(:user).permit(:username, :fullname, :photo, :cover_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def after_login(partial)
    render partial: partial if logged_in?
  end

  def profile_pic(usr, size = '')
    if usr.photo.present?
      image_tag(usr.photo.to_s, alt: usr.username, class: "pr-2 rounded-circle profile-img #{size}")
    else
      image_tag('https://source.unsplash.com/random/60x60',
                alt: 'usr.username', class: 'pr-2 rounded-circle profile-img')
    end
  end

  def cover_pic(usr)
    if usr.cover_image.present?
      image_tag(usr.cover_image.to_s, alt: usr.username)
    else
      image_tag('https://source.unsplash.com/random/700x250', alt: usr.username, class: 'pr-2')
    end
  end

  def different_path_partial
    if logged_in? && params[:action] == 'index'
      render partial: 'shared/right'
    elsif params[:action] == 'show'
      render partial: 'shared/profile_right'
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def show_follower(usr)
    res = ''
    if usr.followers.count.positive?
      res << 'Followed by '
      res << link_to(usr.followers.first.fullname, profile_path(usr.followers.first.username))
    else
      res << '0 follower'
    end
    res.html_safe
  end

  def follow_me(usr, partial)
    return if current_user == usr || current_user.follows.include?(usr)

    render partial: partial, locals: { res: usr }
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitter Redesign</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;300;700&display=swap" rel="stylesheet">
  <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css"
  />
</head>

<body class="bg-light">
  <p class="flash bg-success"><%= flash.notice %></p>
  <p class="flash bg-success"><%= flash.alert %></p>
  <div class="row no-gutters">
    <div class="col-2">
      <%= after_login('shared/left') %>
    </div>
    <div class="col-10">
      <div class="row no-gutters">
        <%= after_login('shared/navbar') %>
      </div>
      <div class="row no-gutters vh-100">
        <div class="col-9">
          <%= yield %>
        </div>
        <div class="col-3 border-left">
          <%= different_path_partial %>
        </div>
      </div>
    </div>
  </div>


</body>
</html>

app/views/opinions/_opinion.html.erb
<div class="d-flex mt-3 pt-3 border-top">
    <div class="pic">
        <%= profile_pic(opinion.author, 'tweet-pic')%>
    </div>
    <div class="text ml-3">
        <h6><strong><%= link_to opinion.author.fullname, profile_path(opinion.author.username) , class: "text-body" %> </strong></h6>
            <p class="card-text"><%= opinion.text %> </p>
    </div>
</div>
<h6 class="text-center mt-2"><em>All comments</em></h6>
<div class='post-comments-section'>
  <% opinion.comments.each do |comment| %>
    <div class="post-comments">
      <p>
        <b><%= comment.user.username %>:</b> <%= comment.content %>
      </p>
      <span> <%= comment.created_at.strftime("%Y/%m/%d") %> </span>
    </div>
  <% end %>
  <%= form_for(opinion.comments.new, url: opinion_comments_path(opinion)) do |form| %>
    <%= form.text_field :content, id: :comment_content, class: 'form-control mb-2', placeholder: 'Add new Comment' %>
    <%= form.submit 'Comment', class: 'btn btn-secondary' %>
  <% end %>
</div>

app/views/opinions/index.html.erb
<div class="d-flex flex-column">
<div>
	<nav class="navbar navbar-expand-lg navbar-light sticky-top border-bottom">
		<div class="container">
			<%= link_to 'Tweet', '#', class: "navbar-brand active" %>
			<ul class="navbar-nav mr-auto">
			<li class="nav-item">
				<%= link_to 'Videos', '#', class: "nav-link" %>
			</li>
			<li class="nav-item">
				<%= link_to 'Photos', '#', class: "nav-link" %>
			</li>
			</ul>
		</div>
	</nav>
</div>

<h3 class="mt-4 px-3"> Suggest Media content </h3>

<div class="card mb-5 mx-3">
	<div class="card-body">
		<%= form_for(@opinion, url: opinion_path) do |f| %>
		<%= f.text_field :text, autofocus: true, class: "form-control", placeholder: "Suggest content by tweet ..." %>
		<% end %>
	</div>
</div>

<div class="card mx-3">
	<div class="card-body">
		<h5 class="card-title border-bottom pb-3">Suggested Content</h5>
		<%= render @opinions %>
	</div>
</div>

</div>

app/views/shared/_follow.html.erb
<%= link_to follow_path(user_id: res.id), class: 'follow_me', method: :post do %>
<svg viewBox="0 0 496 496" class="sidebar-links__icon align-item-end">
    <g>
    <path d="M248,0C111.033,0,0,111.033,0,248c0.154,136.903,111.097,247.846,248,248c136.967,0,248-111.033,248-248S384.967,0,248,0z M248,480C119.87,480,16,376.13,16,248C16.146,119.93,119.93,16.146,248,16c128.13,0,232,103.87,232,232S376.13,480,248,480z"/>
    <path d="M400,240H256V96c0-4.418-3.582-8-8-8s-8,3.582-8,8v144H96c-4.418,0-8,3.582-8,8s3.582,8,8,8h144v144c0,4.418,3.582,8,8,8s8-3.582,8-8V256h144c4.418,0,8-3.582,8-8S404.418,240,400,240z"/>
    </g>
</svg>
<% end %>

app/views/shared/_left.html.erb
<div class="bg-custom-side position-fixed left-side pt-3">
	<div class="nav flex-column flex-nowrap vh-100 overflow-auto text-white p-2">
    <div class="d-flex flex-wrap align-items-center p-2 border-bottom border-dark">
        <%= profile_pic(current_user, 'tweet-pic') %>
        <%= link_to current_user.fullname, profile_path(current_user.username), class: "text-white" %> 
    </div>

    <div class="d-flex flex-wrap justify-content-between p-2 border-bottom border-dark">
    <div class="follow text-center">
      <h5><%= current_user.follows.count %> <br><small>Following</small></h5>
    </div>
    <div class="follow text-center">
      <h5><%= current_user.followers.count %><br><small>Followers</small></h5>
    </div>
    </div>

    <div class="sidebar-links p-2 mt-2 ">
      <a href="#" class="sidebar-links__anchor pr-2">
      <svg viewBox="0 0 24 24" class="sidebar-links__icon">
        <g>
          <path
            d="M22.58 7.35L12.475 1.897c-.297-.16-.654-.16-.95 0L1.425 7.35c-.486.264-.667.87-.405 1.356.18.335.525.525.88.525.16 0 .324-.038.475-.12l.734-.396 1.59 11.25c.216 1.214 1.31 2.062 2.66 2.062h9.282c1.35 0 2.444-.848 2.662-2.088l1.588-11.225.737.398c.485.263 1.092.082 1.354-.404.263-.486.08-1.093-.404-1.355zM12 15.435c-1.795 0-3.25-1.455-3.25-3.25s1.455-3.25 3.25-3.25 3.25 1.455 3.25 3.25-1.455 3.25-3.25 3.25z"
          ></path>
        </g>
      </svg></a>
      <%= link_to "Home", root_path, class: "sidebar-links__anchor " %>
    </div>

    <div class="sidebar-links p-2 mt-2 ">
      <a href="#" class="sidebar-links__anchor pr-2">
      <svg viewBox="0 0 24 24" class="sidebar-links__icon">
        <g>
          <path d="M12 11.816c1.355 0 2.872-.15 3.84-1.256.814-.93 1.078-2.368.806-4.392-.38-2.825-2.117-4.512-4.646-4.512S7.734 3.343 7.354 6.17c-.272 2.022-.008 3.46.806 4.39.968 1.107 2.485 1.256 3.84 1.256zM8.84 6.368c.162-1.2.787-3.212 3.16-3.212s2.998 2.013 3.16 3.212c.207 1.55.057 2.627-.45 3.205-.455.52-1.266.743-2.71.743s-2.255-.223-2.71-.743c-.507-.578-.657-1.656-.45-3.205zm11.44 12.868c-.877-3.526-4.282-5.99-8.28-5.99s-7.403 2.464-8.28 5.99c-.172.692-.028 1.4.395 1.94.408.52 1.04.82 1.733.82h12.304c.693 0 1.325-.3 1.733-.82.424-.54.567-1.247.394-1.94zm-1.576 1.016c-.126.16-.316.246-.552.246H5.848c-.235 0-.426-.085-.552-.246-.137-.174-.18-.412-.12-.654.71-2.855 3.517-4.85 6.824-4.85s6.114 1.994 6.824 4.85c.06.242.017.48-.12.654z"></path>
        </g>
      </svg></a>
      <%= link_to "Profile", profile_path(current_user.username), class: "sidebar-links__anchor" %>
    </div>

    <div class="sidebar-links p-2 mt-2 ">
      <a href="#" class="sidebar-links__anchor pr-2">
      <svg class="sidebar-links__icon" viewBox="0 0 512 512" xml:space="preserve">
        <g><g>
          <path d="M255.15,468.625H63.787c-11.737,0-21.262-9.526-21.262-21.262V64.638c0-11.737,9.526-21.262,21.262-21.262H255.15
            c11.758,0,21.262-9.504,21.262-21.262S266.908,0.85,255.15,0.85H63.787C28.619,0.85,0,29.47,0,64.638v382.724
            c0,35.168,28.619,63.787,63.787,63.787H255.15c11.758,0,21.262-9.504,21.262-21.262
            C276.412,478.129,266.908,468.625,255.15,468.625z"/>
        </g></g>
        <g><g>
          <path d="M505.664,240.861L376.388,113.286c-8.335-8.25-21.815-8.143-30.065,0.213s-8.165,21.815,0.213,30.065l92.385,91.173
            H191.362c-11.758,0-21.262,9.504-21.262,21.262c0,11.758,9.504,21.263,21.262,21.263h247.559l-92.385,91.173
            c-8.377,8.25-8.441,21.709-0.213,30.065c4.167,4.21,9.653,6.336,15.139,6.336c5.401,0,10.801-2.041,14.926-6.124l129.276-127.575
            c4.04-3.997,6.336-9.441,6.336-15.139C512,250.302,509.725,244.88,505.664,240.861z"/>
        </g></g>
      </svg>
      </a>
      <%= link_to "Sign out", logout_path, method: :delete, class: "sidebar-links__anchor" %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-dark bg-custom-top w-100" style="z-index: 3">
	<nav class="navbar navbar-expand-lg navbar-dark sticky-top">
		<div class="container">
			<%= link_to root_path do %> 
				<i class="fas fa-dice-d20 text-white fa-2x"></i>
			<% end %>&nbsp;&nbsp;
			<%= link_to 'Media Fanatics', root_path, class: "navbar-brand" %>
			<button class="navbar-toggler" data-toggle="collapse" data-target="#navbarMenu">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarMenu">
				<ul class="navbar-nav ml-auto">
				<li class="nav-item ml-3">
					<%= link_to '#' do %> 
					<i class="fas fa-search nav-link"></i>
					<% end %>
				</li>
				<li class="nav-item ml-3">
					<%= link_to '#' do %> 
					<i class="fas fa-envelope nav-link"></i>
					<% end %>
				</li>
				<li class="nav-item ml-3">
					<%= link_to '#' do %> 
					<i class="fas fa-pen nav-link"></i>
					<% end %>
				</li>
				<li class="nav-item ml-3">
					<%= link_to edit_user_path(current_user) do %> 
					<svg viewBox="0 0 512 512" class="sidebar-links__icon align-items-end">
					<g><g>
					<path d="M496.659,312.107l-47.061-36.8c0.597-5.675,1.109-12.309,1.109-19.328c0-7.019-0.491-13.653-1.109-19.328l47.104-36.821
							c8.747-6.912,11.136-19.179,5.568-29.397L453.331,85.76c-5.227-9.557-16.683-14.464-28.309-10.176l-55.531,22.293
							c-10.645-7.68-21.803-14.165-33.344-19.349l-8.448-58.901C326.312,8.448,316.584,0,305.086,0h-98.133
							c-11.499,0-21.205,8.448-22.571,19.456l-8.469,59.115c-11.179,5.035-22.165,11.435-33.28,19.349l-55.68-22.357
							C76.52,71.531,64.04,76.053,58.856,85.568L9.854,170.347c-5.781,9.771-3.392,22.464,5.547,29.547l47.061,36.8
							c-0.747,7.189-1.109,13.44-1.109,19.307s0.363,12.117,1.109,19.328l-47.104,36.821c-8.747,6.933-11.115,19.2-5.547,29.397
							l48.939,84.672c5.227,9.536,16.576,14.485,28.309,10.176l55.531-22.293c10.624,7.659,21.781,14.144,33.323,19.349l8.448,58.88
							C185.747,503.552,195.454,512,206.974,512h98.133c11.499,0,21.227-8.448,22.592-19.456l8.469-59.093
							c11.179-5.056,22.144-11.435,33.28-19.371l55.68,22.357c2.688,1.045,5.483,1.579,8.363,1.579c8.277,0,15.893-4.523,19.733-11.563
							l49.152-85.12C507.838,331.349,505.448,319.083,496.659,312.107z M256.019,341.333c-47.061,0-85.333-38.272-85.333-85.333
							s38.272-85.333,85.333-85.333s85.333,38.272,85.333,85.333S303.08,341.333,256.019,341.333z"/>
					</g></g></svg> 
					<% end %>
				</li>
				</ul>
			</div>
		</div>
	</nav>
</div>

app/views/shared/_profile_right.html.erb
<div class="border-left px-1 position-fixed follow-content py-4">
<div class="text-center mb-2">
  <%= follow_me(@user, 'shared/follow') %>
  <%= profile_pic(@user, 'tweet-pic')%>

  <div class="user-info">
    <h5 class="mt-2"><%= link_to @user.fullname, profile_path(@user.username), class: "user-name-p" %> 
      <br>
      <small class="text-gray">@<%= @user.username %></small>
    </h5>
    <div class="stats border-top border-bottom pt-2 d-flex flex-wrap justify-content-around">
      <h5><%= @user.opinions.count %> <br><small>Tweets</small></h5>
      <h5><%= @user.follows.count %> <br><small>Following</small></h5>
      <h5><%= @user.followers.count %><br><small>Followers</small></h5>
    </div>
  </div>
</div>

<h6 class="border-bottom py-3 pl-2">FOLLOWED BY</h6>

<div>
<% @user.followers.each do |follower| %>
    <div class="d-flex flex-row flex-wrap align-items-center mb-2 mt-2 who-to-follow justify-content-around">
      <div class="author">
        <%= profile_pic(follower, 'tweet-pic')%>
      </div>
      <div>
        <h6><strong>
          <%= link_to follower.fullname, profile_path(follower.username), class: "text-dark" %></strong><br>
          <small class="text-gray">@<%= follower.username %></small>
        </h6>
        <%= follow_me(@user, 'shared/follow') %>
      </div>
    </div>
  <% end %>
</div>
</div>

</div>

app/views/shared/_right.html.erb
<div class="px-2 position-fixed" id="sticky-sidebar">
<h6 class="border-bottom py-3">WHO TO FOLLOW</h6>

<% @not_follow.each do |who_to_follow| %>
<div class="d-flex flex-row align-items-center mt-3 mb-4 who-to-follow">
  <div class="author">
  <%= profile_pic(who_to_follow, 'tweet-pic')%>
  </div>
  <div class="follow-content">
    <h6><strong>
      <%= link_to who_to_follow.fullname, profile_path(who_to_follow.username), class: "text-dark" %>
    </strong></h6>
    <small class="text-gray">
      <%= show_follower(who_to_follow) %>
    </small>
  </div>
</div>
<% end %>

<div class="account-type">
  <small class="text-gray">
    <a href="#">Popular accounts</a>&nbsp;&nbsp;
    <a href="#">Find friends</a>
  </small>
</div>

<h6 class="text-gray border-top border-bottom pt-3 pb-3 mt-3 mb-3">TRENDING</h6>

<p><a href="#" class="text-gray"> #interestellar </a></p>
<p><a href="#" class="text-gray"> #LOL </a></p>
<p><a href="#" class="text-gray"> #breakingbad </a></p>

</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row ">
    <div class="d-sm-hidden col-md-6 col-lg-8">
      <ul class="row">
        <% @user.errors.full_messages.each do |message| %>
          <li class="col-12"><%= message %></li>
        <% end %>
      </ul>
    </div>
    <div class="col-sm-12 col-md-8 mt-5">
<h3 class="text-center">Update Account</h3>
<%= form_for(@user, html: {multipart: true}) do |f| %>
  <div class="form-group">
     <%= f.text_field :username, autofocus: true, placeholder: "Enter a username", class: "form-control"  %>
 </div>

<div class="form-group">
     <%= f.text_field :fullname, placeholder: "Enter Fullname", class: "form-control"  %>
 </div>

 <h5 class="border-bottom pb-2">Not mandatory</h5>

  <div class="form-group">
     <%= f.label :photo, "Attach your profile photo" %>
     <%= f.file_field :photo, class: "form-control"  %>
 </div>

   <div class="form-group">
   <%= f.label :cover_image, "Attach your cover image" %>
     <%= f.file_field :cover_image, class: "form-control"  %>
 </div>

 <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
</div>
<% end %>
   </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="my-5 d-flex justify-content-center">

<div class="px-3 py-4 bg-dark border rounded-3">

<h2 class="text-center text-primary">Sign Up</h2>

<div class="d-sm-hidden col-md-6 col-lg-8">
  <ul class="row">
    <% @user.errors.full_messages.each do |message| %>
      <li class="col-12"><%= message %></li>
    <% end %>
  </ul>

  <div class="">
  <%= form_for(@user, ) do |f| %>

    <div class="form-group">
      <%= f.text_field :username, autocomplete: "username", class: "form-control", placeholder: "Username" %>
    </div>

    <div class="form-group">
      <%= f.text_field :fullname, autocomplete: "Enter full name", class: "form-control", placeholder: "Full name" %>
    </div>

    <h5 class="border-bottom pb-2 text-white">Optional</h5>

    <div class="form-group">
      <%= f.label :photo, "Attach your profile photo", class: "text-primary" %>
      <%= f.file_field :photo, class: "form-control"  %>
    </div>

    <div class="form-group">
      <%= f.label :cover_image, "Attach your cover image", class: "text-primary" %>
      <%= f.file_field :cover_image, class: "form-control"  %>
    </div>

    <div class="actions">
      <%= f.submit class: "btn btn-primary" %>
      <p><small><em>Already have an account?</em></small> <%= link_to 'Sign in', sign_in_path %></p>
    </div>
  <% end %>
  </div>
</div>

</div>
</div>

app/views/users/show.html.erb
<div class="cover_image bg-gray mb-2" >
  <%= cover_pic(@user) %>
</div>

<div class="row">
<div class="col">
  <nav class="navbar navbar-expand-lg navbar-light">
    <div class="container">
      <%= link_to 'Tweet', '#', class: "navbar-brand active border-bottom border-primary" %>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to 'Photos', '#', class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Following', '#', class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Followers', '#', class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Favourites', '#', class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Lists', '#', class: "nav-link" %>
        </li>
      </ul>
    </div>
  </nav>
</div>
</div>

<div class="card mb-5 mt-3">
  <div class="card-body">
  <h5 class="card-title border-bottom pb-3">MAKE A SUGGESTION TO <%= @user.fullname.upcase %></h5>
  <%= form_for(@opinion, url: opinion_path) do |f| %>
      <%= f.text_field :text, autofocus: true, class: "form-control", placeholder: "Enter a message..." %>
  <% end %>
  </div>
</div>

<div class="card">
  <div class="card-body">
    <h5 class="card-title border-bottom pb-3">ALL CONTENT SUGGESTED BY <%= @user.fullname.upcase %></h5>
    <%= render @opinions %>
  </div>
</div>